itsu-token:
  enable: true
  table-class: com.itsu.itsutoken.table.SimpleTableSample
  type: simple
  web-register: true
  system:
    encrypt-base64: true
  init:
    auto-create-table: true
    schema-location: classpath:schema/simpleSchema.sql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_db
    username: root
    password: 123456
debug: true
#    driver-class-name: com.mysql.jdbc.Driver